In [ ]:
import pandas as pd
titanic = pd.read_csv('train.csv')
titanic.head()

titanic.isna().sum()/len(titanic)

from fastai.tabular.all import *

In [ ]:
# cont_cat_split(titanic,dep_var='')
titanic

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]

In [ ]:
con_cols,cat_cols=cont_cat_split(titanic,dep_var='Survived')

In [ ]:
con_cols

['PassengerId', 'Age', 'Fare']

In [ ]:
con_cols = ['Age', 'Fare']

In [ ]:
titanic[cat_cols].nunique()

Pclass        3
Name        891
Sex           2
SibSp         7
Parch         7
Ticket      681
Cabin       147
Embarked      3
dtype: int64

In [ ]:
titanic.shape

(891, 12)

In [ ]:
cat_cols_to_keep =  ['Pclass', 'Sex', 'SibSp', 'Parch',  'Embarked']

In [ ]:
titanic[cat_cols_to_keep].nunique()

Pclass      3
Sex         2
SibSp       4
Parch       4
Embarked    3
dtype: int64

In [ ]:
titanic = titanic.dropna()

In [ ]:
titanic.isna().sum()/len(titanic)

PassengerId    0.0
Survived       0.0
Pclass         0.0
Name           0.0
Sex            0.0
Age            0.0
SibSp          0.0
Parch          0.0
Ticket         0.0
Fare           0.0
Cabin          0.0
Embarked       0.0
dtype: float64

In [ ]:
titanic[cat_cols_to_keep + con_cols ]

Pclass     Sex  SibSp  Parch Embarked   Age     Fare
1         1  female      1      0        C  38.0  71.2833
3         1  female      1      0        S  35.0  53.1000
6         1    male      0      0        S  54.0  51.8625
10        3  female      1      1        S   4.0  16.7000
11        1  female      0      0        S  58.0  26.5500
..      ...     ...    ...    ...      ...   ...      ...
871       1  female      1      1        S  47.0  52.5542
872       1    male      0      0        S  33.0   5.0000
879       1  female      0      1        C  56.0  83.1583
887       1  female      0      0        S  19.0  30.0000
889       1    male      0      0        C  26.0  30.0000

[183 rows x 7 columns]

In [ ]:
TabularPandas?

Init signature:
TabularPandas(
    df,
    procs=None,
    cat_names=None,
    cont_names=None,
    y_names=None,
    y_block=None,
    splits=None,
    do_setup=True,
    device=None,
    inplace=False,
    reduce_memory=True,
)
Docstring:      A `Tabular` object with transforms
File:           ~/.local/lib/python3.11/site-packages/fastai/tabular/core.py
Type:           type
Subclasses:     


In [ ]:
procs= [Categorify,Normalize]

In [ ]:
RandomSplitter?
# TabularPandas(titanic,procs,cat_cols_to_keep,con_cols,'Survived',)

Signature: RandomSplitter(valid_pct=0.2, seed=None)
Docstring: Create function that splits `items` between train/val with `valid_pct` randomly.
File:      ~/.local/lib/python3.11/site-packages/fastai/data/transforms.py
Type:      function


In [ ]:
splits = RandomSplitter()(range_of(titanic))

In [ ]:
to = TabularPandas(titanic, procs=procs, cat_names=cat_cols_to_keep, 
                  cont_names=con_cols, y_names='Survived', splits=splits)

In [ ]:
to.show(4)

In [ ]:
to.xs

Pclass  Sex  SibSp  Parch  Embarked       Age      Fare
340       2    2      2      2         3 -2.054206 -0.754632
305       1    2      2      3         3 -2.121277  1.223575
806       1    2      1      1         3  0.243585 -1.164296
710       1    1      1      1         1 -0.687952 -0.384292
823       3    1      1      2         3 -0.501644 -0.967736
..      ...  ...    ...    ...       ...       ...       ...
621       1    2      2      1         3  0.429893 -0.336235
802       1    2      2      3         3 -1.495284  0.726463
336       1    2      2      1         3 -0.377439 -0.114925
671       1    2      2      1         3 -0.253234 -0.344967
781       1    1      2      1         3 -1.122669 -0.266186

[183 rows x 7 columns]

In [ ]:
to.xs.shape

(183, 7)

In [ ]:
pd.DataFrame(to.xs)

Pclass  Sex  SibSp  Parch  Embarked       Age      Fare
340       2    2      2      2         3 -2.054206 -0.754632
305       1    2      2      3         3 -2.121277  1.223575
806       1    2      1      1         3  0.243585 -1.164296
710       1    1      1      1         1 -0.687952 -0.384292
823       3    1      1      2         3 -0.501644 -0.967736
..      ...  ...    ...    ...       ...       ...       ...
621       1    2      2      1         3  0.429893 -0.336235
802       1    2      2      3         3 -1.495284  0.726463
336       1    2      2      1         3 -0.377439 -0.114925
671       1    2      2      1         3 -0.253234 -0.344967
781       1    1      2      1         3 -1.122669 -0.266186

[183 rows x 7 columns]

In [ ]:
w = torch.randn(to.xs.shape[1])
result = torch.tensor(to.xs.values) @ w
result[:5]

tensor([1.4576, 2.0369, 1.9673, 0.3302, 3.0161])

In [ ]:
result

tensor([ 1.4576,  2.0369,  1.9673,  0.3302,  3.0161, -0.7962,  3.4981, -0.5885,
         0.0633,  1.6076,  0.5319,  1.4603,  0.8321,  2.2092,  2.1276,  2.2237,
         0.4013,  0.0038,  0.9674,  0.8958,  2.1900,  2.1259,  2.1761,  2.1341,
         0.9783,  2.1481,  2.1268,  1.9620, -0.7990,  2.0647,  1.0887,  1.2067,
         0.5622, -0.1001,  0.6726,  0.3269,  1.9139,  0.7217,  2.1526,  1.7288,
         2.3949,  0.8668,  0.7006, -0.7123,  0.8046,  0.5629,  2.1908,  2.0876,
         2.2141,  2.1877,  0.6952, -0.8046,  2.0700,  1.2749,  1.4437,  2.4674,
         3.0843,  0.4013,  0.4765,  2.0812,  3.0384,  2.0874, -0.6042,  0.9218,
         2.3177,  2.0325,  2.9910,  2.9402,  2.8311,  2.6908,  0.3734,  2.0535,
         2.6707,  1.4621, -0.6124,  0.3916,  1.9890,  1.8943,  1.9688,  0.4554,
         2.0720, -0.2664, -0.7690,  0.3945,  0.6233, -0.8736,  2.2724,  0.4484,
         3.0201,  0.8583,  1.0141,  3.3619,  1.6475,  1.8939,  1.6426,  3.0856,
        -0.1659,  1.9701, -0.2691, -0.36

In [ ]:
result.shape

torch.Size([183])

In [ ]:
torch.clip(result,min=0)

tensor([1.4576, 2.0369, 1.9673, 0.3302, 3.0161, 0.0000, 3.4981, 0.0000, 0.0633,
        1.6076, 0.5319, 1.4603, 0.8321, 2.2092, 2.1276, 2.2237, 0.4013, 0.0038,
        0.9674, 0.8958, 2.1900, 2.1259, 2.1761, 2.1341, 0.9783, 2.1481, 2.1268,
        1.9620, 0.0000, 2.0647, 1.0887, 1.2067, 0.5622, 0.0000, 0.6726, 0.3269,
        1.9139, 0.7217, 2.1526, 1.7288, 2.3949, 0.8668, 0.7006, 0.0000, 0.8046,
        0.5629, 2.1908, 2.0876, 2.2141, 2.1877, 0.6952, 0.0000, 2.0700, 1.2749,
        1.4437, 2.4674, 3.0843, 0.4013, 0.4765, 2.0812, 3.0384, 2.0874, 0.0000,
        0.9218, 2.3177, 2.0325, 2.9910, 2.9402, 2.8311, 2.6908, 0.3734, 2.0535,
        2.6707, 1.4621, 0.0000, 0.3916, 1.9890, 1.8943, 1.9688, 0.4554, 2.0720,
        0.0000, 0.0000, 0.3945, 0.6233, 0.0000, 2.2724, 0.4484, 3.0201, 0.8583,
        1.0141, 3.3619, 1.6475, 1.8939, 1.6426, 3.0856, 0.0000, 1.9701, 0.0000,
        0.0000, 0.8907, 0.4511, 1.0082, 0.8138, 2.1274, 0.0000, 0.0000, 2.3442,
        2.5732, 1.3052, 0.7721, 0.4099, 

In [ ]:
to.procs

Pipeline: RegressionSetup -- {'c': None} -> Categorify -- {'classes': {'Pclass': ['#na#', np.int8(1), np.int8(2), np.int8(3)], 'Sex': ['#na#', 'female', 'male'], 'SibSp': ['#na#', np.int8(0), np.int8(1), np.int8(2), np.int8(3)], 'Parch': ['#na#', np.int8(0), np.int8(1), np.int8(2), np.int8(4)], 'Embarked': ['#na#', 'C', 'Q', 'S']}} -> Normalize -- {'mean': None, 'std': None, 'axes': (0, 2, 3), 'means': {'Age': np.float32(35.077686), 'Fare': np.float32(73.893906)}, 'stds': {'Age': np.float32(16.102417), 'Fare': np.float32(63.466576)}}

In [ ]:
to.ys

Survived
340         1
305         1
806         0
710         1
823         1
..        ...
621         1
802         1
336         0
671         0
781         1

[183 rows x 1 columns]

In [ ]:
result.shape

torch.Size([183])

In [ ]:
to.ys.shape

(183, 1)

In [ ]:
target = torch.tensor(to.ys.values).squeeze()
print(target.shape)
diff = (result - target)**2

torch.Size([183])


In [ ]:
diff.shape

torch.Size([183])

In [ ]:
diff.mean()

tensor(2.0463)

how can i claculate gradient and subtarct from paratemerts

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Let's calculate the gradient and update the parameters using gradient descent. First, let's set up our parameters with `requires_grad=True` and define a simple loss function:

```python
w = torch.randn(to.xs.shape[1], requires_grad=True)
lr = 0.01  # learning rate

# Forward pass
def forward(): 
    pred = torch.tensor(to.xs.values) @ w
    target = torch.tensor(to.ys.values).squeeze()
    loss = ((pred - target)**2).mean()
    return loss, pred

# Calculate loss and gradients
loss, pred = forward()
loss.backward()

# Print the gradient
print(w.grad)

# Update parameters using gradient descent
with torch.no_grad():
    w -= lr * w.grad
    
# Zero gradients for next step
w.grad.zero_()
```

This will:
1. Create weights with gradient tracking
2. Calculate predictions and loss
3. Compute gradients with backward()
4. Update parameters using gradient descent
5. Reset gradients for the next iteration

You can wrap this in a loop to train for multiple epochs.

In [ ]:
w = torch.randn(to.xs.shape[1], requires_grad=True)
lr = 0.01  # learning rate

# Forward pass
def forward(): 
    pred = torch.tensor(to.xs.values) @ w
    target = torch.tensor(to.ys.values).squeeze()
    loss = ((pred - target)**2).mean()
    return loss, pred

# Calculate loss and gradients
loss, pred = forward()
loss.backward()
print(loss)

# Print the gradient
print(w.grad)

# Update parameters using gradient descent
with torch.no_grad():
    w -= lr * w.grad
    
# Zero gradients for next step
w.grad.zero_()


tensor(50.9002, grad_fn=<MeanBackward0>)
tensor([15.3188, 20.5081, 21.2386, 22.5742, 31.7944, -0.7923,  4.3342])


tensor([0., 0., 0., 0., 0., 0., 0.])

In [ ]:
w

tensor([-1.1156, -0.1701,  2.1025,  2.0463, -1.5240,  0.3675, -1.8785],
       requires_grad=True)

In [ ]:
for i in range(5):
    def forward(): 
        pred = torch.tensor(to.xs.values) @ w
        target = torch.tensor(to.ys.values).squeeze()
        loss = ((pred - target)**2).mean()
        return loss, pred
    
    print(pred[0:5])

    # Calculate loss and gradients
    loss, pred = forward()
    loss.backward()
    print(loss)

    # Print the gradient
    print(w.grad)

    # Update parameters using gradient descent
    with torch.no_grad():
        w -= lr * w.grad
        
    # Zero gradients for next step
    w.grad.zero_()

tensor([ 9.5322, 13.8919,  6.2051,  4.1973,  5.8065], grad_fn=<SliceBackward0>)
tensor(28.1018, grad_fn=<MeanBackward0>)
tensor([10.7473, 14.7645, 15.5368, 16.7429, 22.6584, -0.7100,  3.9493])
tensor([ 7.0020, 11.2029,  4.3022,  3.0941,  3.5621], grad_fn=<SliceBackward0>)
tensor(16.1624, grad_fn=<MeanBackward0>)
tensor([ 7.4543, 10.6232, 11.4165, 12.5250, 16.0770, -0.6452,  3.6408])
tensor([5.1817, 9.2440, 2.9446, 2.2999, 1.9567], grad_fn=<SliceBackward0>)
tensor(9.8786, grad_fn=<MeanBackward0>)
tensor([ 5.0834,  7.6377,  8.4374,  9.4713, 11.3381, -0.5934,  3.3886])
tensor([3.8732, 7.8124, 1.9798, 1.7285, 0.8119], grad_fn=<SliceBackward0>)
tensor(6.5424, grad_fn=<MeanBackward0>)
tensor([ 3.3776,  5.4859,  6.2816,  7.2577,  7.9281, -0.5510,  3.1780])
tensor([ 2.9338e+00,  6.7617e+00,  1.2979e+00,  1.3178e+00, -1.0989e-03],
       grad_fn=<SliceBackward0>)
tensor(4.7442, grad_fn=<MeanBackward0>)
tensor([ 2.1514,  3.9353,  4.7200,  5.6506,  5.4763, -0.5157,  2.9984])


In [ ]:
splits

((#147) [np.int64(70),np.int64(55),np.int64(169),np.int64(146),np.int64(172),np.int64(56),np.int64(80),np.int64(111),np.int64(125),np.int64(112),np.int64(15),np.int64(31),np.int64(23),np.int64(105),np.int64(93),np.int64(63),np.int64(75),np.int64(81),np.int64(38),np.int64(49)...],
 (#36) [np.int64(32),np.int64(77),np.int64(176),np.int64(122),np.int64(153),np.int64(113),np.int64(51),np.int64(163),np.int64(165),np.int64(96),np.int64(108),np.int64(114),np.int64(39),np.int64(52),np.int64(97),np.int64(84),np.int64(94),np.int64(101),np.int64(47),np.int64(2)...])

In [ ]:
to.valid.xs

Pclass  Sex  SibSp  Parch  Embarked       Age      Fare
194       1    1      1      1         1  0.554098 -0.727518
377       1    2      1      3         1 -0.501644  2.168166
862       1    1      1      1         3  0.802508 -0.755747
591       1    1      2      1         1  1.050918  0.068899
737       1    2      1      1         1 -0.004825  6.908129
556       1    1      2      1         1  0.802508 -0.540346
291       1    1      2      1         1 -0.998464  0.270777
779       1    1      1      2         3  0.491995  2.165606
782       1    2      1      1         3 -0.377439 -0.691607
486       1    1      2      1         3 -0.004825  0.253773
536       1    2      1      1         3  0.616200 -0.745966
558       1    1      2      2         3  0.243585  0.090695
230       1    1      2      1         3 -0.004825  0.150963
292       2    2      1      1         1  0.057278 -0.961434
487       1    2      1      1         1  1.423532 -0.696334
434       1    2      2      1         3  0.926713 -0.283518
473       2    1      1      1         1 -0.750054 -0.946990
504       1    1      1      1         3 -1.184772  0.198626
268       1    1      1      2         3  1.423532  1.253709
6         1    2      1      1         3  1.175123 -0.347134
209       1    2      1      1         1  0.305688 -0.675850
124       1    2      1      2         3  1.175123  0.053471
215       1    1      2      1         1 -0.253234  0.620501
498       1    1      2      3         3 -0.625849  1.223575
690       1    2      2      1         3 -0.253234 -0.266186
609       1    1      1      1         3  0.305688  1.253709
492       1    2      1      1         3  1.237225 -0.683728
571       1    1      3      1         3  1.113020 -0.353173
679       1    2      1      2         1  0.057278  6.908129
625       1    2      1      1         3  1.609840 -0.655039
151       1    1      2      1         3 -0.812157 -0.114925
621       1    2      2      1         3  0.429893 -0.336235
802       1    2      2      3         3 -1.495284  0.726463
336       1    2      2      1         3 -0.377439 -0.114925
671       1    2      2      1         3 -0.253234 -0.344967
781       1    1      2      1         3 -1.122669 -0.266186

In [ ]:
to.train.xs

Pclass  Sex  SibSp  Parch  Embarked       Age      Fare
340       2    2      2      2         3 -2.054206 -0.754632
305       1    2      2      3         3 -2.121277  1.223575
806       1    2      1      1         3  0.243585 -1.164296
710       1    1      1      1         1 -0.687952 -0.384292
823       3    1      1      2         3 -0.501644 -0.967736
..      ...  ...    ...    ...       ...       ...       ...
339       1    2      1      1         3  0.616200 -0.604947
581       1    1      2      2         1  0.243585  0.582817
75        3    2      1      1         3 -0.625849 -1.043761
62        1    2      2      1         3  0.616200  0.150963
715       3    2      1      1         3 -0.998464 -1.043761

[147 rows x 7 columns]

In [ ]:
torch.tensor(to.valid.xs.values) @  w

tensor([ 0.3581,  4.8330,  0.2269,  1.0737,  3.5772,  0.9150,  1.6878,  2.8173,
         0.8249,  1.3644,  0.5431,  2.6731,  1.3266, -0.7854,  0.4041,  1.1849,
        -0.8309,  1.1014,  2.2365,  0.5426,  0.7061,  2.1240,  1.6201,  4.7529,
         1.5022,  1.0969,  0.4024,  1.4002,  4.9949,  0.3148,  1.4415,  1.2964,
         5.0626,  1.5905,  1.4732,  1.4677], grad_fn=<MvBackward0>)

In [ ]:
w

tensor([-1.4518,  0.2635,  0.5535,  1.4341, -0.0277, -0.2634,  0.3678],
       requires_grad=True)

In [ ]:
preds =torch.tensor(to.valid.xs.values) @  w

In [ ]:
preds.clip(min=0,max=1)

tensor([0.3581, 1.0000, 0.2269, 1.0000, 1.0000, 0.9150, 1.0000, 1.0000, 0.8249,
        1.0000, 0.5431, 1.0000, 1.0000, 0.0000, 0.4041, 1.0000, 0.0000, 1.0000,
        1.0000, 0.5426, 0.7061, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.4024,
        1.0000, 1.0000, 0.3148, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
       grad_fn=<ClampBackward1>)

In [ ]:
to.valid.ys.values

array([[1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1]], dtype=int8)

In [ ]:
torch.tensor(to.valid.ys.values) == torch.tensor(to.valid.ys.values)



tensor([[True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True]])